### PR TITLE
Review

### PR DESCRIPTION
**Pull request by francksefu**
Add all features of to-do list exercise
Check if I follow KISS, DRY and YAGNI for better programmation

### CODE REVIEW

**Comment by edgardsoza** [comment]
You did a good job with this project and I would like to add the following advices, so that you can improve it. 
https://github.com/francksefu/webpack-review-R/blob/8924908c8843ecbf8f85bd941a9fe4c2c0e4ed15/src/array-feature.js#L67
https://github.com/francksefu/webpack-review-R/blob/8924908c8843ecbf8f85bd941a9fe4c2c0e4ed15/src/array-feature.js#L73
https://github.com/francksefu/webpack-review-R/blob/8924908c8843ecbf8f85bd941a9fe4c2c0e4ed15/src/array-feature.js#L82
https://github.com/francksefu/webpack-review-R/blob/8924908c8843ecbf8f85bd941a9fe4c2c0e4ed15/src/array-feature.js#L10
https://github.com/francksefu/webpack-review-R/blob/8924908c8843ecbf8f85bd941a9fe4c2c0e4ed15/src/index.js#L27

You could have used forEach method instead of looping with for. 

https://github.com/francksefu/webpack-review-R/blob/8924908c8843ecbf8f85bd941a9fe4c2c0e4ed15/src/index.js#L1
This function was from the original task, it should not be included in this one.

**Comment by francksefu** [comment]
> You did a good job with this project and I would like to add the following advices, so that you can improve it.
> 
> https://github.com/francksefu/webpack-review-R/blob/8924908c8843ecbf8f85bd941a9fe4c2c0e4ed15/src/array-feature.js#L67
> 
> 
> https://github.com/francksefu/webpack-review-R/blob/8924908c8843ecbf8f85bd941a9fe4c2c0e4ed15/src/array-feature.js#L73
> 
> 
> https://github.com/francksefu/webpack-review-R/blob/8924908c8843ecbf8f85bd941a9fe4c2c0e4ed15/src/array-feature.js#L82
> 
> 
> https://github.com/francksefu/webpack-review-R/blob/8924908c8843ecbf8f85bd941a9fe4c2c0e4ed15/src/array-feature.js#L10
> 
> 
> https://github.com/francksefu/webpack-review-R/blob/8924908c8843ecbf8f85bd941a9fe4c2c0e4ed15/src/index.js#L27
> 
> You could have used forEach method instead of looping with for.
> 
> https://github.com/francksefu/webpack-review-R/blob/8924908c8843ecbf8f85bd941a9fe4c2c0e4ed15/src/index.js#L1
> 
> 
> This function was from the original task, it should not be included in this one.

For the comment in line 27 in the index.js file, I think It would be better if I use for loop instead of forEach, forEach it's a good way if the instruction inside the loop it's just one instruction, but in our case (line 27) we have much instruction

**Comment by francksefu** [comment]
Thank you for reviewing my code, I had finish to implements all suggest you give to me, can I merge now ??

**Comment by edgardsoza** [comment]
> Thank you for reviewing my code, I had finish to implements all suggest you give to me, can I merge now ??

Sure!!

**Pull request merged**
